### ISSUE TITLE
打开Ner后,部分场景会出现异常

### ISSUE THREAD

**Issue by zhouxw536** [mayabot/mynlp#14]
Exception in thread "main" java.lang.IllegalStateException: row: 6358 len 42 select is null
	at com.mayabot.nlp.segment.wordnet.Wordpath$1.computeNext(Wordpath.java:105)
	at com.mayabot.nlp.segment.wordnet.Wordpath$1.computeNext(Wordpath.java:82)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.mayabot.nlp.segment.plugins.collector.SentenceCollector.collect(SentenceCollector.kt:28)
	at com.mayabot.nlp.segment.pipeline.PipelineLexer.scan(PipelineLexer.java:136)

**Comment by jimichan** [comment]
fix in 3.0.2
