### ISSUE TITLE
fastText加载C原版的压缩模型后，分类出错

### ISSUE THREAD

**Issue by jimichan** [mayabot/mynlp#21]
```
com.mayabot.nlp.fasttext.TestCModelFTZKt
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1569793
	at com.mayabot.nlp.fasttext.blas.QuantMatrix.addRowToVector(QuantMatrix.kt:153)
	at com.mayabot.nlp.fasttext.blas.Matrix$DefaultImpls.addRowToVector$default(Matrix.kt:24)
	at com.mayabot.nlp.fasttext.Model.computeHidden(Model.kt:31)
	at com.mayabot.nlp.fasttext.Model.predict(Model.kt:63)
	at com.mayabot.nlp.fasttext.FastText.predict(FastText.kt:78)
	at com.mayabot.nlp.fasttext.FastText.predict(FastText.kt:62)
	at com.mayabot.nlp.fasttext.TestCModelFTZKt.main(TestCModelFTZ.kt:10)
	at com.mayabot.nlp.fasttext.TestCModelFTZKt.main(TestCModelFTZ.kt)
```

**Comment by jimichan** [comment]
FIXED in RELEASE 3.1.6
